platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: tools
  - name: application
  - name: build-files

run:
  path: ./tools/tasks/ls/task.sh